// ============================================================
// YOTEC — Output Repository Panel
// ============================================================

import { store } from '../state.js';
import { QAEngine } from '../ai-engine.js';

export function renderOutputs(container) {
    const state = store.state;
    const outputs = state.outputs;

    container.innerHTML = `
    <div class="page-header">
      <div>
        <div class="page-title">📦 Artifact Repository</div>
        <div class="page-subtitle">All functional outputs generated by YOTEC AI workers</div>
      </div>
      <div style="display:flex;gap:8px;align-items:center;">
        <button class="btn btn-primary btn-sm" onclick="window._yotec.switchPanel('execute')">⚡ New Execution</button>
      </div>
    </div>

    <div class="outputs-grid" style="display:grid;grid-template-columns:repeat(auto-fill, minmax(320px, 1fr));gap:20px;">
      ${outputs.length ? outputs.map(outputCard).join('') : `
        <div class="empty-state" style="grid-column:1/-1;">
          <div class="empty-state-icon">📦</div>
          <div class="empty-state-text">No artifacts generated yet.<br>Go to Task Execution to generate one.</div>
        </div>
      `}
    </div>
  `;

    // Attach QA review listeners
    container.querySelectorAll('.qa-validate-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const output = store.state.outputs.find(o => o.id === btn.dataset.oid);
            if (!output) return;
            btn.textContent = 'Reviewing...';
            btn.disabled = true;
            setTimeout(() => {
                QAEngine.review(output);
                renderOutputs(container);
            }, 1000);
        });
    });
}

function outputCard(out) {
    const date = new Date(out.timestamp).toLocaleString();
    const worker = store.getWorker(out.workerId);
    const workerName = worker ? worker.name : out.workerId;

    let statusBadge = '<span class="badge badge-pending">Pending QA</span>';
    if (out.qaStatus === 'approved') statusBadge = '<span class="badge badge-completed">QA Approved</span>';
    if (out.qaStatus === 'rejected') statusBadge = '<span class="badge badge-revision">QA Rejected</span>';

    let previewHTML = '';
    if (out.format === 'svg') {
        previewHTML = `<div style="padding:10px;background:#000;border-radius:4px;display:flex;justify-content:center;">${out.content}</div>`;
    } else if (out.format === 'ts' || out.format === 'json') {
        previewHTML = `<pre style="font-family:var(--font-mono);font-size:0.65rem;color:var(--text-secondary);background:var(--bg-deep);padding:10px;border-radius:4px;overflow:hidden;max-height:150px;white-space:pre-wrap;">${out.content}</pre>`;
    } else {
        // Markdown / text
        const textPreview = out.content.replace(/<[^>]*>?/gm, '').substring(0, 150) + '...';
        previewHTML = `<div style="font-size:0.75rem;color:var(--text-secondary);line-height:1.5;">${textPreview}</div>`;
    }

    return `
    <div class="card" style="display:flex;flex-direction:column;gap:12px;">
      <div style="display:flex;justify-content:space-between;align-items:flex-start;">
        <div>
          <div style="font-size:0.9rem;font-weight:700;color:var(--text-primary);margin-bottom:4px;">${out.title}</div>
          <div style="font-size:0.7rem;color:var(--text-muted);">Generated by ${workerName} (${out.taskType})</div>
        </div>
        ${statusBadge}
      </div>
      
      <div style="flex:1;border:1px solid var(--border-subtle);border-radius:4px;padding:4px;background:var(--bg-surface);">
        ${previewHTML}
      </div>
      
      <div style="display:flex;justify-content:space-between;align-items:center;margin-top:auto;border-top:1px solid var(--border-subtle);padding-top:12px;">
        <div style="font-size:0.65rem;color:var(--text-muted);">${date}</div>
        <div style="display:flex;gap:6px;">
          ${out.qaStatus === 'pending' ? `<button class="btn btn-secondary btn-sm qa-validate-btn" data-oid="${out.id}" style="padding:4px 8px;font-size:0.7rem;">🛡️ Validate</button>` : ''}
          <button class="btn btn-primary btn-sm" onclick="window._yotec.downloadArtifact('${out.id}')" style="padding:4px 8px;font-size:0.7rem;">📥 Download .${out.format}</button>
        </div>
      </div>
    </div>
  `;
}

// Global download helper for the app.js to bind
export function downloadArtifact(id) {
    const output = store.state.outputs.find(o => o.id === id);
    if (!output) return;

    const blob = new Blob([output.content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `YOTEC-${output.title.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.${output.format}`;
    a.click();
    URL.revokeObjectURL(url);
}
